
// Mock data for booklist
export const booklist = [
    { id: "1", cat1Id: "1", cat2Id: "1", name: "ML Book 11", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title1", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "2", cat1Id: "1", cat2Id: "1", name: "ML Book 12", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title12", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"    },
    { id: "3", cat1Id: "1", cat2Id: "1", name: "ML Book 13", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title13", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"    },
    { id: "4", cat1Id: "1", cat2Id: "1", name: "ML Book 14", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title14", author:"author1" , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"   },
    { id: "5", cat1Id: "1", cat2Id: "1", name: "ML Book 15", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title15", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "6", cat1Id: "1", cat2Id: "1", name: "ML Book 16", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title17", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "7", cat1Id: "1", cat2Id: "2", name: "ML Book 17", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title81", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "8", cat1Id: "1", cat2Id: "2", name: "ML Book 18", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title19", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "9", cat1Id: "1", cat2Id: "2", name: "ML Book 1a", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title1a", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "10",cat1Id: "1", cat2Id: "2", name: "ML Book 1b", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title1b", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "11",cat1Id: "1", cat2Id: "3", name: "ML Book 1c", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title1c", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "12",cat1Id: "1", cat2Id: "3", name: "ML Book 1d", cover: "https://aidres.com/gallery/yangchenchen1/IMG_0527.JPG", title:"title1d", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
];

