const UL = "https://aidres.com/gallery/yangchenchen1/";

// Mock data for booklist
export const booklist = [
    { id: "111", name: "ML Book 11", cover: `${UL}IMG_1096.PNG`, title:"title1", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "112", name: "ML Book 12", cover: `${UL}IMG_1096.PNG`, title:"title12", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"    },
    { id: "113", name: "ML Book 13", cover: `${UL}IMG_1096.PNG`, title:"title13", author:"author1", summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"    },
    { id: "121", name: "ML Book 14", cover: `${UL}IMG_1096.PNG`, title:"title14", author:"author1" , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"   },
    { id: "122", name: "ML Book 15", cover: `${UL}IMG_1096.PNG`, title:"title15", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "123", name: "ML Book 16", cover: `${UL}IMG_1096.PNG`, title:"title17", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "124", name: "ML Book 17", cover: `${UL}IMG_1096.PNG`, title:"title81", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "125", name: "ML Book 18", cover: `${UL}IMG_1096.PNG`, title:"title19", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "211", name: "ML Book 1a", cover: `${UL}IMG_1096.PNG`, title:"title1a", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "212",name: "ML Book 1b", cover: `${UL}IMG_1096.PNG`, title:"title1b", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "213",name: "ML Book 1c", cover: `${UL}IMG_1096.PNG`, title:"title1c", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
    { id: "214",name: "ML Book 1d", cover: `${UL}IMG_1096.PNG`, title:"title1d", author:"author1"  , summary:"Beautiful is better than ugly.Explicit is better than implicit.Simple is better than complex.Complex is better than complicated.Flat is better than nested.Sparse is better than dense.Readability counts.Special cases aren't special"  },
];

